FROM python:3.11-slim

WORKDIR /app
COPY packages ./packages
COPY apps ./apps
COPY services ./services
COPY services/classical-nlp-service/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

CMD ["uvicorn", "main:app", "--app-dir", "apps/api-gateway", "--host", "0.0.0.0", "--port", "8000"]
