FROM python:3.11-slim

WORKDIR /app
COPY packages ./packages
COPY services/transformer-service ./services/transformer-service
RUN pip install --no-cache-dir -r services/transformer-service/requirements.txt

CMD ["python", "-m", "http.server", "8002"]
